version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  show-versions:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: 10.19.0
      - run: echo NODE Version && node --version
      - run: echo NPM Version && npm --version
workflows:
  test-and-deploy:
    jobs:
      - node/test 14.15.1:
          version: 14.15.1
          filters:
            branches:
              only:
                - master
      - node/test 12.19.1:
          version: 12.19.1
          filters:
            branches:
              only:
                - master
      - node/test 10.22.1:
          version: 10.22.1
          filters:
            branches:
              only:
                - master
      - node/test 8.17.0:
          version: 8.17.0
          filters:
            branches:
              only:
                - master
      - node/test 6.17.1:
          version: 6.17.1
          filters:
            branches:
              only:
                - master
      - node/test 4.9.1:
          version: 4.9.1
          filters:
            branches:
              only:
                - master
      - node/test 3.3.1:
          version: 3.3.1
          filters:
            branches:
              only:
                - master
          
      # - show-versions:
      #     requires:
      #       - node/test
# version: 2.1
# orbs:
#   node: circleci/node@4.1.0
# jobs:
#   my-job-name:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       # - checkout
#       - node/install:
#           # install-yarn: true
#       - run: node --version
# workflows:
#   my-workflow-name:
#     jobs:
#       - my-job-name
