version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  show-versions:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          name: 'Test'
          path: 'test'
      # - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      # - run: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      # - run: nvm install 10.14.0
      # - node/install
      # node-version: 10.19.0
      - run: echo NODE Version && node --version
      - run: echo NPM Version && npm --version
workflows:
  test-and-deploy:
    jobs:
      - show-versions
      # - node/test:
      #     # version: 14.15.1
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     # requires:
      #     #   - node/test
# version: 2.1
# orbs:
#   node: circleci/node@4.1.0
# jobs:
#   my-job-name:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       # - checkout
#       - node/install:
#           # install-yarn: true
#       - run: node --version
# workflows:
#   my-workflow-name:
#     jobs:
#       - my-job-name
