version: 2.1
orbs:
  node: circleci/node@4.1.0
# jobs:
#   show-versions:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - node/install:
#           node-version: 10.19.0
#       - run: echo NODE Version && node --version
#       - run: echo NPM Version && npm --version
workflows:
  test-and-deploy:
    jobs:
      - node/test:
          version: 14.15.1
          filters:
            branches:
              only:
                - master
      # - show-versions
