orbs:
  heroku: circleci/heroku@1.1
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test-and-deploy:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - master
          # requires:
          #   - node/test
