version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  show-versions:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: 10.19.0
      - run: echo NODE Version && node --version
      - run: echo NPM Version && npm --version
workflows:
  test-and-deploy:
    jobs:
      - node/test:
          version: 14.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 12.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 10.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 8.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 6.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 4.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 2.10.0
          filters:
            branches:
              only:
                - master
      - node/test:
          version: 0.10.0
          filters:
            branches:
              only:
                - master
          
      # - show-versions:
      #     requires:
      #       - node/test
# version: 2.1
# orbs:
#   node: circleci/node@4.1.0
# jobs:
#   my-job-name:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       # - checkout
#       - node/install:
#           # install-yarn: true
#       - run: node --version
# workflows:
#   my-workflow-name:
#     jobs:
#       - my-job-name
